'use client';
import {FormEvent,useState} from 'react';

type Lang='ar'|'en';
type Role='operations'|'supervisor'|'support'|'accountant'|'developer'|'business';
const paths:Record<Role,string>={operations:'/operations',supervisor:'/operations',support:'/operations',accountant:'/finance',developer:'/settings',business:'/business'};
const copy={ar:{title:'تحديث رمز الدخول',sub:'لأمان الحساب يجب تغيير الرمز الافتراضي بعد أول دخول. حساب المطور غير مشمول بهذا الإجراء.',a:'الرمز الجديد',b:'تأكيد الرمز',save:'حفظ ومتابعة',bad:'يجب أن يكون الرمز 6 خانات على الأقل وأن يتطابق.',same:'لا يمكن استخدام الرمز الافتراضي مرة أخرى.',done:'تم حفظ الرمز لهذا المتصفح.',portal:'بوابة الدخول'},en:{title:'Update access code',sub:'For account security, update the default access code after first login. Developer account is excluded.',a:'New code',b:'Confirm code',save:'Save and continue',bad:'Code must be at least 6 characters and both fields must match.',same:'The default code cannot be reused.',done:'Access code saved for this browser.',portal:'Portal'}};
async function digest(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function storeKey(role:string,username:string){return `jnbk_staff_access_${role}_${username||role}`}
export default function FirstLogin(){const params=new URLSearchParams(typeof window==='undefined'?'':window.location.search);const lang:Lang=params.get('lang')==='en'?'en':'ar';const ar=lang==='ar';const t=copy[lang];const role=(typeof window!=='undefined'?(sessionStorage.getItem('jnbk_active_role')||'operations'):'operations') as Role;const profile=typeof window!=='undefined'?JSON.parse(sessionStorage.getItem('jnbk_staff_profile')||'{}'):{};const username=profile.username||role;const[v,setV]=useState('');const[c,setC]=useState('');const[msg,setMsg]=useState('');async function submit(e:FormEvent){e.preventDefault();if(v.length<6||v!==c){setMsg(t.bad);return}if(v==='123456'){setMsg(t.same);return}localStorage.setItem(storeKey(role,username),await digest(v));sessionStorage.removeItem('jnbk_must_change_password');setMsg(t.done);setTimeout(()=>{window.location.href=`${paths[role]||'/'}?lang=${lang}`},600)}return <main dir={ar?'rtl':'ltr'} style={{textAlign:ar?'right':'left'}}><section className='hero'><div className='heroTop'><div><p className='kicker'>Jnbk جنبك</p><h1>{t.title}</h1><p>{t.sub}</p></div><a className='languageSwitch' href={`/portal?lang=${lang}`}>{t.portal}</a></div></section>{msg?<div className={msg===t.done?'notice success':'notice error'}>{msg}</div>:null}<section className='panel'><form className='formGrid' onSubmit={submit}><input type='password' value={v} onChange={e=>setV(e.target.value)} placeholder={t.a}/><input type='password' value={c} onChange={e=>setC(e.target.value)} placeholder={t.b}/><button className='primaryAction' type='submit'>{t.save}</button></form></section></main>}
