type Lang='ar'|'en';
type Driver={id:string;name:string;online?:boolean;verified?:boolean;cityId?:string};
type Ride={id:string;status:string;estimatedFare:number;createdAt?:string};
type SupportRequest={id:string;category:string;message:string;lang?:string;status:string};
const fallbackDrivers:Driver[]=[{id:'driver_1',name:'Mohammed Ahmed',online:true,verified:true,cityId:'rufaa'},{id:'driver_2',name:'Ali Altayeb',online:true,verified:true,cityId:'rufaa'}];
const fallbackSupport:SupportRequest[]=[{id:'support_preview_1',category:'Request new city',message:'Preview support requests appear here after backend connection.',lang:'en',status:'OPEN'}];
const copy={ar:{title:'لوحة إدارة التطبيق',sub:'مساحة التشغيل اليومية: الرحلات، السائقين، الدعم، ومؤشرات الأداء.',back:'الرئيسية',dev:'لوحة المطور',support:'طلبات الدعم',drivers:'السائقون',rides:'الرحلات',tasks:'تقسيم المهام اليومي',shift:'مسؤول الوردية',supportRole:'الدعم الفني',finance:'المحاسبة',owner:'مالك التطبيق',online:'متصل',offline:'غير متصل',verified:'معتمد',pending:'قيد المراجعة',toggle:'English'},en:{title:'App Management Dashboard',sub:'Daily operations workspace: rides, drivers, support, and performance indicators.',back:'Home',dev:'Developer panel',support:'Support requests',drivers:'Drivers',rides:'Rides',tasks:'Daily task split',shift:'Shift lead',supportRole:'Support team',finance:'Finance',owner:'App owner',online:'Online',offline:'Offline',verified:'Verified',pending:'Pending',toggle:'العربية'}};
async function apiGet<T>(path:string,fallback:T):Promise<T>{const apiUrl=process.env.NEXT_PUBLIC_API_URL;if(!apiUrl)return fallback;try{const r=await fetch(`${apiUrl}${path}`,{cache:'no-store'});return r.ok?await r.json():fallback}catch{return fallback}}
function short(m:string){return m.length>70?m.slice(0,70)+'...':m}
export default async function Operations({searchParams}:{searchParams?:{lang?:string}}){const lang:Lang=searchParams?.lang==='en'?'en':'ar';const t=copy[lang];const rtl=lang==='ar';const drivers=await apiGet<Driver[]>('/api/drivers',fallbackDrivers);const rides=await apiGet<Ride[]>('/api/rides',[]);const support=await apiGet<SupportRequest[]>('/api/support',fallbackSupport);const open=support.filter(x=>x.status==='OPEN'||x.status==='IN_REVIEW').length;return <main dir={rtl?'rtl':'ltr'} style={{textAlign:rtl?'right':'left'}}><section className='hero'><div className='heroTop'><div><p className='kicker'>Jnbk جنبك</p><h1>{t.title}</h1><p>{t.sub}</p></div><div className='topActions'><a className='languageSwitch' href='/'>{t.back}</a><a className='languageSwitch' href={`/settings?lang=${lang}`}>{t.dev}</a><a className='languageSwitch' href={`?lang=${lang==='ar'?'en':'ar'}`}>{t.toggle}</a></div></div></section><section className='grid settingsGrid'><div className='card'><p>{t.rides}</p><strong>{rides.length}</strong></div><div className='card'><p>{t.drivers}</p><strong>{drivers.length}</strong></div><div className='card'><p>{t.support}</p><strong>{open}</strong></div><div className='card'><p>Status</p><strong>Live</strong></div></section><section className='panel'><h2>{t.tasks}</h2><div className='table'><div className='row'><span>{t.shift}</span><span>{lang==='ar'?'متابعة الرحلات والسائقين والبلاغات العاجلة':'Track rides, drivers, urgent issues'}</span><span>Daily</span><b>Active</b></div><div className='row'><span>{t.supportRole}</span><span>{lang==='ar'?'إغلاق طلبات الدعم وتوثيق الشكاوى':'Close support tickets and document complaints'}</span><span>Daily</span><b>Active</b></div><div className='row'><span>{t.finance}</span><span>{lang==='ar'?'مراجعة الإيرادات والمصروفات ونسب الأرباح':'Review revenue, costs, and profit shares'}</span><span>Monthly</span><b>Review</b></div><div className='row'><span>{t.owner}</span><span>{lang==='ar'?'اعتماد المدن الجديدة والترقيات المدفوعة':'Approve new cities and paid upgrades'}</span><span>As needed</span><b>Approve</b></div></div></section><section className='panel'><h2>{t.support}</h2><div className='table'>{support.length===0?<div className='empty'>-</div>:support.slice(0,8).map(x=><div className='row' key={x.id}><span>{x.category}</span><span>{short(x.message)}</span><span>{x.lang||'ar'}</span><b>{x.status}</b></div>)}</div></section><section className='panel'><h2>{t.drivers}</h2><div className='table'>{drivers.slice(0,8).map(d=><div className='row' key={d.id}><span>{d.name}</span><span>{d.cityId||'city'}</span><span>{d.verified?t.verified:t.pending}</span><b>{d.online?t.online:t.offline}</b></div>)}</div></section></main>}
