type Lang='ar'|'en';
type Task={id:string;titleAr:string;titleEn:string;ownerAr:string;ownerEn:string;priority:'high'|'medium'|'low';status:'active'|'testing'|'planned'|'done';dueAr:string;dueEn:string;workspace:string;noteAr:string;noteEn:string};
const copy={ar:{title:'مركز المهام النشط',sub:'لوحة تشغيل منظمة لمتابعة مهام Jnbk جنبك حسب المسؤول، الأولوية، الحالة، ومساحة العمل.',back:'الرئيسية',portal:'بوابة الدخول',toggle:'English',summary:'ملخص التنفيذ',tasks:'المهام المفعلة',roles:'توزيع المسؤوليات',handover:'آلية التسليم والتصعيد',quality:'معايير الجودة',active:'نشط',testing:'اختبار',planned:'مخطط',done:'مكتمل',high:'عالية',medium:'متوسطة',low:'منخفضة',owner:'المسؤول',priority:'الأولوية',status:'الحالة',due:'الموعد',workspace:'المساحة',note:'ملاحظة'},en:{title:'Active Tasks Center',sub:'A structured operations board for Jnbk tasks by owner, priority, status, and workspace.',back:'Home',portal:'Portal',toggle:'العربية',summary:'Execution summary',tasks:'Activated tasks',roles:'Responsibility split',handover:'Handover and escalation',quality:'Quality standards',active:'Active',testing:'Testing',planned:'Planned',done:'Done',high:'High',medium:'Medium',low:'Low',owner:'Owner',priority:'Priority',status:'Status',due:'Due',workspace:'Workspace',note:'Note'}};
const tasks:Task[]=[
{id:'T-01',titleAr:'ضبط Firebase ومتغيرات البيئة',titleEn:'Configure Firebase environment variables',ownerAr:'المطور',ownerEn:'Developer',priority:'high',status:'active',dueAr:'اليوم',dueEn:'Today',workspace:'/system',noteAr:'تفعيل Firestore للتطبيق ولوحة الإدارة',noteEn:'Enable Firestore for mobile and admin'},
{id:'T-02',titleAr:'اختبار بوابة الدخول لكل الأدوار',titleEn:'Test staff portal for all roles',ownerAr:'مدير التشغيل',ownerEn:'Operations manager',priority:'high',status:'testing',dueAr:'اليوم',dueEn:'Today',workspace:'/portal',noteAr:'كلمة الموظفين 123456 عدا المطور',noteEn:'Staff password is 123456 except developer'},
{id:'T-03',titleAr:'مراجعة ملفات الجوكية واعتماد الجاهز',titleEn:'Review and approve ready driver files',ownerAr:'مسؤول الجوكية',ownerEn:'Driver officer',priority:'high',status:'active',dueAr:'يوميًا',dueEn:'Daily',workspace:'/drivers',noteAr:'التحقق من الضامن والمركبة والرقم الوطني',noteEn:'Verify guarantor, vehicle, and national ID'},
{id:'T-04',titleAr:'متابعة الرحلات وطلبات الدعم',titleEn:'Monitor rides and support requests',ownerAr:'مشرف الوردية',ownerEn:'Shift supervisor',priority:'high',status:'active',dueAr:'كل وردية',dueEn:'Every shift',workspace:'/operations',noteAr:'تصعيد البلاغات العاجلة فورًا',noteEn:'Escalate urgent cases immediately'},
{id:'T-05',titleAr:'قفل النسب والعقود وأرشفة القديم',titleEn:'Lock agreements and archive old contracts',ownerAr:'الإدارة والاتفاقات',ownerEn:'Business admin',priority:'medium',status:'done',dueAr:'تم',dueEn:'Done',workspace:'/business',noteAr:'أي تعديل بعقد جديد فقط',noteEn:'Any change requires a new contract'},
{id:'T-06',titleAr:'تجهيز تقرير الإيرادات والمصروفات',titleEn:'Prepare revenue and cost report',ownerAr:'المحاسب',ownerEn:'Accountant',priority:'medium',status:'active',dueAr:'أسبوعيًا',dueEn:'Weekly',workspace:'/finance',noteAr:'مطابقة النقد والتحويلات والاشتراكات',noteEn:'Reconcile cash, transfers, and subscriptions'},
{id:'T-07',titleAr:'اختبار APK على هاتفين',titleEn:'Test APK on two phones',ownerAr:'المطور',ownerEn:'Developer',priority:'medium',status:'planned',dueAr:'قبل الإطلاق',dueEn:'Before launch',workspace:'Expo / EAS',noteAr:'اختبار الأزرار العربية والإنجليزية',noteEn:'Test Arabic and English buttons'},
{id:'T-08',titleAr:'تجهيز رقم سنتر وخطة SMS',titleEn:'Prepare call center number and SMS plan',ownerAr:'مدير التشغيل',ownerEn:'Operations manager',priority:'low',status:'planned',dueAr:'مرحلة الإطلاق',dueEn:'Launch phase',workspace:'SMS',noteAr:'للأحياء ذات الإنترنت الضعيف',noteEn:'For weak internet areas'}
];
const roles=[['الإدارة العليا','Owner','اعتماد العقود والمدن والنسب المغلقة','Approve contracts, cities, and locked shares'],['مدير التشغيل','Operations','توزيع الورديات ومراقبة الأداء اليومي','Assign shifts and monitor daily performance'],['مشرف الوردية','Supervisor','متابعة الرحلات والبلاغات الحية','Track live rides and incidents'],['مسؤول الجوكية','Driver officer','مراجعة ملفات الجوكية واعتماد الجاهز','Review driver files and approve ready ones'],['مسؤول العملاء','Support','الشكاوى والمفقودات والتصعيد','Complaints, lost items, and escalation'],['المحاسب','Accountant','الإيرادات والمصروفات والتقارير','Revenue, costs, and reports'],['المطور','Developer','Firebase وAPK والأخطاء التقنية','Firebase, APK, and technical fixes']];
const quality=[['No broken buttons','كل زر يجب أن يفتح صفحة أو ينفذ إجراء واضح'],['Role-based access','كل صفحة إدارية حسب صلاحية واضحة'],['Arabic-first UX','الواجهة العربية تعمل مثل الإنجليزية دون أعطال'],['Autosave','أي نموذج طويل يحفظ تلقائيًا'],['Audit trail','أي عقد جديد يؤرشف القديم ولا يغيره مباشرة']];
function labelStatus(status:Task['status'],lang:Lang){const t=copy[lang];return t[status]}
function labelPriority(priority:Task['priority'],lang:Lang){const t=copy[lang];return t[priority]}
export default function Workflow({searchParams}:{searchParams?:{lang?:string}}){const lang:Lang=searchParams?.lang==='en'?'en':'ar';const ar=lang==='ar';const t=copy[lang];const active=tasks.filter(x=>x.status==='active').length;const testing=tasks.filter(x=>x.status==='testing').length;const done=tasks.filter(x=>x.status==='done').length;const planned=tasks.filter(x=>x.status==='planned').length;return <main dir={ar?'rtl':'ltr'} style={{textAlign:ar?'right':'left'}}><section className='hero'><div className='heroTop'><div><p className='kicker'>Jnbk جنبك</p><h1>{t.title}</h1><p>{t.sub}</p></div><div className='topActions'><a className='languageSwitch' href='/'>{t.back}</a><a className='languageSwitch' href={`/portal?lang=${lang}`}>{t.portal}</a><a className='languageSwitch' href={`/workflow?lang=${ar?'en':'ar'}`}>{t.toggle}</a></div></div></section><section className='grid settingsGrid'><div className='card'><p>{t.active}</p><strong>{active}</strong></div><div className='card'><p>{t.testing}</p><strong>{testing}</strong></div><div className='card'><p>{t.done}</p><strong>{done}</strong></div><div className='card'><p>{t.planned}</p><strong>{planned}</strong></div></section><section className='panel'><h2>{t.tasks}</h2><div className='table'>{tasks.map(item=><div className='row' key={item.id}><span><b>{item.id}</b><br/>{ar?item.titleAr:item.titleEn}</span><span>{t.owner}: {ar?item.ownerAr:item.ownerEn}<br/>{t.priority}: {labelPriority(item.priority,lang)}</span><span>{t.workspace}: {item.workspace}<br/>{t.due}: {ar?item.dueAr:item.dueEn}</span><b>{labelStatus(item.status,lang)}<br/><small>{ar?item.noteAr:item.noteEn}</small></b></div>)}</div></section><section className='panel'><h2>{t.roles}</h2><div className='table'>{roles.map(r=><div className='row' key={r[1]}><span>{ar?r[0]:r[1]}</span><span>{ar?r[2]:r[3]}</span><span>{t.workspace}</span><b>{t.active}</b></div>)}</div></section><section className='panel'><h2>{t.handover}</h2><div className='table'><div className='row'><span>{ar?'بلاغ عادي':'Normal issue'}</span><span>{ar?'مسؤول العملاء':'Support'}</span><span>{ar?'يغلق أو يصعد للمشرف':'Close or escalate to supervisor'}</span><b>24h</b></div><div className='row'><span>{ar?'بلاغ عاجل':'Urgent issue'}</span><span>{ar?'مشرف الوردية':'Shift supervisor'}</span><span>{ar?'تصعيد فوري لمدير التشغيل':'Immediate escalation to operations manager'}</span><b>Now</b></div><div className='row'><span>{ar?'تعديل اتفاق':'Agreement change'}</span><span>{ar?'الإدارة':'Business admin'}</span><span>{ar?'عقد جديد وأرشفة القديم':'New contract and archive old one'}</span><b>Locked</b></div></div></section><section className='panel'><h2>{t.quality}</h2><div className='table'>{quality.map(r=><div className='row' key={r[0]}><span>{r[0]}</span><span>{r[1]}</span><span>{ar?'قاعدة تشغيل':'Operating rule'}</span><b>{ar?'إلزامي':'Required'}</b></div>)}</div></section></main>}
