type Lang='ar'|'en';
type AppConfig={countries:{id:string;nameEn:string;currency:string}[];cities:{id:string;countryId:string;nameEn:string;zones?:unknown[];zonesEn?:string[]}[];vehicleTypes:{id:string;nameEn:string;baseFare:number;perKmFare:number;minimumFare:number}[]};
type Driver={id:string;name:string;online?:boolean;verified?:boolean;cityId?:string};
type Ride={id:string;status:string;estimatedFare:number};
type SupportRequest={id:string;category:string;message:string;lang?:string;status:string};
const fallbackConfig:AppConfig={countries:[{id:'sd',nameEn:'Sudan',currency:'SDG'},{id:'sa',nameEn:'Saudi Arabia',currency:'SAR'}],cities:[{id:'rufaa',countryId:'sd',nameEn:'Rufaa',zonesEn:['Market','Hospital','Station','Schools']},{id:'khartoum',countryId:'sd',nameEn:'Khartoum',zonesEn:['Khartoum','Bahri','Omdurman']},{id:'dammam',countryId:'sa',nameEn:'Dammam',zonesEn:['Central','Corniche','Airport']}],vehicleTypes:[{id:'rickshaw',nameEn:'Rickshaw',baseFare:500,perKmFare:300,minimumFare:1000},{id:'car',nameEn:'Car',baseFare:900,perKmFare:550,minimumFare:1800},{id:'van',nameEn:'Van',baseFare:1200,perKmFare:700,minimumFare:2500}]};
const fallbackDrivers:Driver[]=[{id:'driver_1',name:'Mohammed Ahmed',online:true,verified:true,cityId:'rufaa'},{id:'driver_2',name:'Ali Altayeb',online:true,verified:true,cityId:'rufaa'}];
const fallbackSupport:SupportRequest[]=[{id:'support_preview_1',category:'Request new city',message:'Preview support requests appear here after backend connection.',lang:'en',status:'OPEN'}];
const copy={ar:{cc:'مركز التحكم',dash:'لوحة الإدارة',hero:'لوحة تشغيل مباشرة لإدارة المدن والخدمات والسائقين والرحلات وطلبات الدعم والأسعار.',trips:'إجمالي الرحلات',active:'السائقون النشطون',open:'طلبات الدعم المفتوحة',cities:'المدن',summary:'ملخص التشغيل',done:'الرحلات المكتملة',revenue:'إجمالي الإيراد التقديري',support:'طلبات الدعم',none:'لا توجد طلبات دعم حتى الآن.',areas:'المدن ومناطق الإطلاق',zones:'مناطق',ready:'جاهزة',pricing:'أنواع المركبات والأسعار',base:'الأساسي',min:'الحد الأدنى',drivers:'السائقون',verified:'معتمد',pending:'قيد المراجعة',online:'متصل',offline:'غير متصل',toggle:'English'},en:{cc:'CONTROL CENTER',dash:'Operations Dashboard',hero:'Live-ready admin view for cities, services, drivers, rides, support requests, and pricing.',trips:'Trips total',active:'Active drivers',open:'Support open',cities:'Cities',summary:'Operations summary',done:'Completed rides',revenue:'Total estimated revenue',support:'Support requests',none:'No support requests yet.',areas:'Cities and launch areas',zones:'zones',ready:'Ready',pricing:'Vehicle types and pricing',base:'Base',min:'Minimum',drivers:'Drivers',verified:'Verified',pending:'Pending',online:'Online',offline:'Offline',toggle:'العربية'}};
async function apiGet<T>(path:string,fallback:T):Promise<T>{const apiUrl=process.env.NEXT_PUBLIC_API_URL;if(!apiUrl)return fallback;try{const r=await fetch(`${apiUrl}${path}`,{cache:'no-store'});return r.ok?await r.json():fallback}catch{return fallback}}
function countryName(c:AppConfig,id:string){return c.countries.find(x=>x.id===id)?.nameEn||id.toUpperCase()}
function zoneCount(c:AppConfig['cities'][number]){return c.zones?.length||c.zonesEn?.length||0}
function shortMessage(m:string){return m.length>74?`${m.slice(0,74)}...`:m}
export default async function Dashboard({searchParams}:{searchParams?:{lang?:string}}){const lang:Lang=searchParams?.lang==='en'?'en':'ar';const t=copy[lang];const rtl=lang==='ar';const config=await apiGet<AppConfig>('/api/config',fallbackConfig);const drivers=await apiGet<Driver[]>('/api/drivers',fallbackDrivers);const rides=await apiGet<Ride[]>('/api/rides',[]);const supportRequests=await apiGet<SupportRequest[]>('/api/support',fallbackSupport);const activeDrivers=drivers.filter(d=>d.online).length;const completedRides=rides.filter(r=>r.status==='COMPLETED').length;const openSupport=supportRequests.filter(x=>x.status==='OPEN'||x.status==='IN_REVIEW').length;const totalRevenue=rides.reduce((s,r)=>s+Number(r.estimatedFare||0),0);const metrics=[[t.trips,String(rides.length)],[t.active,String(activeDrivers)],[t.open,String(openSupport)],[t.cities,String(config.cities.length)]];return <main dir={rtl?'rtl':'ltr'} style={{textAlign:rtl?'right':'left'}}><section className='hero'><div className='heroTop'><div><p className='kicker'>Jnbk جنبك {t.cc}</p><h1>{t.dash}</h1><p>{t.hero}</p></div><a className='languageSwitch' href={`?lang=${lang==='ar'?'en':'ar'}`}>{t.toggle}</a></div></section><section className='grid'>{metrics.map(([l,v])=><div className='card' key={l}><p>{l}</p><strong>{v}</strong></div>)}</section><section className='panel'><h2>{t.summary}</h2><div className='table'><div className='row'><span>{t.done}</span><span>{completedRides}</span><span>{t.revenue}</span><b>{totalRevenue} SDG</b></div></div></section><section className='panel'><h2>{t.support}</h2><div className='table'>{supportRequests.length===0?<div className='empty'>{t.none}</div>:supportRequests.slice(0,8).map(x=><div className='row' key={x.id}><span>{x.category}</span><span>{shortMessage(x.message)}</span><span>{x.lang||'ar'}</span><b>{x.status}</b></div>)}</div></section><section className='panel'><h2>{t.areas}</h2><div className='table'>{config.cities.map(c=><div className='row' key={c.id}><span>{c.nameEn}</span><span>{countryName(config,c.countryId)}</span><span>{zoneCount(c)} {t.zones}</span><b>{t.ready}</b></div>)}</div></section><section className='panel'><h2>{t.pricing}</h2><div className='table'>{config.vehicleTypes.map(x=><div className='row' key={x.id}><span>{x.nameEn}</span><span>{t.base} {x.baseFare}</span><span>{x.perKmFare} / km</span><b>{t.min} {x.minimumFare}</b></div>)}</div></section><section className='panel'><h2>{t.drivers}</h2><div className='table'>{drivers.slice(0,8).map(d=><div className='row' key={d.id}><span>{d.name}</span><span>{d.cityId||'city'}</span><span>{d.verified?t.verified:t.pending}</span><b>{d.online?t.online:t.offline}</b></div>)}</div></section></main>}
