import { getFirebaseCollection, isFirebaseConfigured } from './lib/firebase';

type Lang='ar'|'en';
type AppConfig={countries:{id:string;nameEn:string;currency:string}[];cities:{id:string;countryId:string;nameEn:string;zones?:unknown[];zonesEn?:string[]}[];vehicleTypes:{id:string;nameEn:string;baseFare:number;perKmFare:number;minimumFare:number}[]};
type Driver={id:string;name?:string;online?:boolean;verified?:boolean;cityId?:string;status?:string};
type Ride={id:string;status?:string;estimatedFare?:number};
type SupportRequest={id:string;category?:string;message?:string;lang?:string;status?:string};
const fallbackConfig:AppConfig={countries:[{id:'sd',nameEn:'Sudan',currency:'SDG'}],cities:[{id:'rufaa',countryId:'sd',nameEn:'Rufaa',zonesEn:['Market','Hospital','Station']}],vehicleTypes:[{id:'rickshaw',nameEn:'Rickshaw',baseFare:500,perKmFare:300,minimumFare:1000}]};
const fallbackDrivers:Driver[]=[{id:'driver_1',name:'Preview Driver',online:true,verified:true,cityId:'rufaa'}];
const fallbackSupport:SupportRequest[]=[{id:'support_preview_1',category:'Preview',message:'Firebase/backend requests appear here.',lang:'en',status:'OPEN'}];
const copy={ar:{cc:'مركز التحكم',dash:'بوابة التحكم الموحدة',hero:'رابط موحد لكل لوحات العمل مع تسجيل دخول منفصل حسب الصلاحية.',portal:'تسجيل الدخول الموحد',portalDesc:'اختر حساب الموظف المناسب من البوابة.',operations:'لوحة التشغيل',settings:'لوحة المطور',business:'الإدارة والاتفاقات',workflow:'تنسيق العمل',finance:'المحاسب والمالية',launch:'جاهزية الإطلاق',system:'إعدادات النظام',trips:'إجمالي الرحلات',active:'السائقون النشطون',open:'طلبات الدعم المفتوحة',cities:'المدن',summary:'ملخص سريع',done:'الرحلات المكتملة',revenue:'إجمالي الإيراد التقديري',source:'مصدر البيانات',firebase:'Firebase Firestore',backend:'Backend API',preview:'Preview',toggle:'English'},en:{cc:'CONTROL CENTER',dash:'Unified Control Portal',hero:'One link for all workspaces with separate login per role.',portal:'Unified login',portalDesc:'Choose the right staff account from the portal.',operations:'Operations',settings:'Developer Panel',business:'Business',workflow:'Workflow',finance:'Finance',launch:'Launch',system:'System Settings',trips:'Trips total',active:'Active drivers',open:'Support open',cities:'Cities',summary:'Quick summary',done:'Completed rides',revenue:'Total estimated revenue',source:'Data source',firebase:'Firebase Firestore',backend:'Backend API',preview:'Preview',toggle:'العربية'}};
async function apiGet<T>(path:string,fallback:T):Promise<T>{const apiUrl=process.env.NEXT_PUBLIC_API_URL;if(!apiUrl)return fallback;try{const r=await fetch(`${apiUrl}${path}`,{cache:'no-store'});return r.ok?await r.json():fallback}catch{return fallback}}
async function loadList<T>(collectionName:string,apiPath:string,fallback:T[]):Promise<T[]>{return isFirebaseConfigured()?getFirebaseCollection<T>(collectionName,fallback):apiGet<T[]>(apiPath,fallback)}
export default async function Dashboard({searchParams}:{searchParams?:{lang?:string}}){const lang:Lang=searchParams?.lang==='en'?'en':'ar';const t=copy[lang];const rtl=lang==='ar';const config=await apiGet<AppConfig>('/api/config',fallbackConfig);const drivers=await loadList<Driver>('driverApplications','/api/drivers',fallbackDrivers);const rides=await loadList<Ride>('rides','/api/rides',[]);const supportRequests=await loadList<SupportRequest>('supportRequests','/api/support',fallbackSupport);const source=isFirebaseConfigured()?t.firebase:(process.env.NEXT_PUBLIC_API_URL?t.backend:t.preview);const activeDrivers=drivers.filter(d=>d.online||d.status==='approved').length;const completedRides=rides.filter(r=>r.status==='COMPLETED'||r.status==='completed').length;const openSupport=supportRequests.filter(x=>!x.status||x.status==='OPEN'||x.status==='IN_REVIEW'||x.status==='open').length;const totalRevenue=rides.reduce((s,r)=>s+Number(r.estimatedFare||0),0);const metrics=[[t.trips,String(rides.length)],[t.active,String(activeDrivers)],[t.open,String(openSupport)],[t.cities,String(config.cities.length)]];return <main dir={rtl?'rtl':'ltr'} style={{textAlign:rtl?'right':'left'}}><section className='hero'><div className='heroTop'><div><p className='kicker'>Jnbk جنبك {t.cc}</p><h1>{t.dash}</h1><p>{t.hero}</p></div><div className='topActions'><a className='languageSwitch' href={`?lang=${lang==='ar'?'en':'ar'}`}>{t.toggle}</a><a className='languageSwitch' href={`/portal?lang=${lang}`}>{t.portal}</a><a className='languageSwitch' href={`/system?lang=${lang}`}>{t.system}</a></div></div></section><section className='grid'>{metrics.map(([l,v])=><div className='card' key={l}><p>{l}</p><strong>{v}</strong></div>)}</section><section className='panel'><h2>{t.source}</h2><p className='muted'>{source}</p></section><section className='panel'><h2>{t.portal}</h2><p className='muted'>{t.portalDesc}</p><a className='primaryAction' style={{display:'inline-block',marginTop:12,textDecoration:'none'}} href={`/portal?lang=${lang}`}>{t.portal}</a></section><section className='grid devGrid'>{[[t.operations,'/portal'],[t.settings,'/portal'],[t.business,'/portal'],[t.finance,'/finance'],[t.workflow,'/workflow'],[t.launch,'/launch']].map(([label,path])=><div className='panel' key={label}><h2>{label}</h2><a className='primaryAction' style={{display:'inline-block',marginTop:12,textDecoration:'none'}} href={`${path}?lang=${lang}`}>{label}</a></div>)}<div className='panel'><h2>{t.summary}</h2><div className='table'><div className='row'><span>{t.done}</span><span>{completedRides}</span><span>{t.revenue}</span><b>{totalRevenue} SDG</b></div></div></div></section></main>}
