type Lang='ar'|'en';
type AppConfig={countries:{id:string;nameEn:string;currency:string}[];cities:{id:string;countryId:string;nameEn:string;zones?:unknown[];zonesEn?:string[]}[];vehicleTypes:{id:string;nameEn:string;baseFare:number;perKmFare:number;minimumFare:number}[]};
type Driver={id:string;name:string;online?:boolean;verified?:boolean;cityId?:string};
type Ride={id:string;status:string;estimatedFare:number};
type SupportRequest={id:string;category:string;message:string;lang?:string;status:string};
const fallbackConfig:AppConfig={countries:[{id:'sd',nameEn:'Sudan',currency:'SDG'},{id:'sa',nameEn:'Saudi Arabia',currency:'SAR'}],cities:[{id:'rufaa',countryId:'sd',nameEn:'Rufaa',zonesEn:['Market','Hospital','Station','Schools']},{id:'khartoum',countryId:'sd',nameEn:'Khartoum',zonesEn:['Khartoum','Bahri','Omdurman']},{id:'dammam',countryId:'sa',nameEn:'Dammam',zonesEn:['Central','Corniche','Airport']}],vehicleTypes:[{id:'rickshaw',nameEn:'Rickshaw',baseFare:500,perKmFare:300,minimumFare:1000},{id:'car',nameEn:'Car',baseFare:900,perKmFare:550,minimumFare:1800},{id:'van',nameEn:'Van',baseFare:1200,perKmFare:700,minimumFare:2500}]};
const fallbackDrivers:Driver[]=[{id:'driver_1',name:'Mohammed Ahmed',online:true,verified:true,cityId:'rufaa'},{id:'driver_2',name:'Ali Altayeb',online:true,verified:true,cityId:'rufaa'}];
const fallbackSupport:SupportRequest[]=[{id:'support_preview_1',category:'Request new city',message:'Preview support requests appear here after backend connection.',lang:'en',status:'OPEN'}];
const copy={ar:{cc:'مركز التحكم',dash:'بوابة التحكم الموحدة',hero:'رابط موحد لكل لوحات العمل مع تسجيل دخول منفصل حسب الصلاحية.',portal:'تسجيل الدخول الموحد',portalDesc:'اختر إدارة التطبيق أو حساب المطور أو قسم الاتفاقات من بوابة واحدة.',operations:'لوحة إدارة التطبيق',operationsDesc:'تشغيل يومي: الرحلات، السائقين، الدعم، وتقسيم مهام الفريق.',settings:'لوحة المطور',settingsDesc:'إعدادات تقنية: المدن، المناطق، المركبات، الأسعار، والربط.',business:'القسم الهام',businessDesc:'الاشتراكات، الروابط، نسب الأرباح، والاتفاقات.',trips:'إجمالي الرحلات',active:'السائقون النشطون',open:'طلبات الدعم المفتوحة',cities:'المدن',summary:'ملخص سريع',done:'الرحلات المكتملة',revenue:'إجمالي الإيراد التقديري',toggle:'English'},en:{cc:'CONTROL CENTER',dash:'Unified Control Portal',hero:'One link for all workspaces with separate login per role.',portal:'Unified login',portalDesc:'Choose app management, developer account, or agreements from one portal.',operations:'App Management',operationsDesc:'Daily operations: rides, drivers, support, and team task split.',settings:'Developer Panel',settingsDesc:'Technical settings: cities, zones, vehicles, pricing, and integrations.',business:'Important Section',businessDesc:'Subscriptions, links, profit share, and agreements.',trips:'Trips total',active:'Active drivers',open:'Support open',cities:'Cities',summary:'Quick summary',done:'Completed rides',revenue:'Total estimated revenue',toggle:'العربية'}};
async function apiGet<T>(path:string,fallback:T):Promise<T>{const apiUrl=process.env.NEXT_PUBLIC_API_URL;if(!apiUrl)return fallback;try{const r=await fetch(`${apiUrl}${path}`,{cache:'no-store'});return r.ok?await r.json():fallback}catch{return fallback}}
export default async function Dashboard({searchParams}:{searchParams?:{lang?:string}}){const lang:Lang=searchParams?.lang==='en'?'en':'ar';const t=copy[lang];const rtl=lang==='ar';const config=await apiGet<AppConfig>('/api/config',fallbackConfig);const drivers=await apiGet<Driver[]>('/api/drivers',fallbackDrivers);const rides=await apiGet<Ride[]>('/api/rides',[]);const supportRequests=await apiGet<SupportRequest[]>('/api/support',fallbackSupport);const activeDrivers=drivers.filter(d=>d.online).length;const completedRides=rides.filter(r=>r.status==='COMPLETED').length;const openSupport=supportRequests.filter(x=>x.status==='OPEN'||x.status==='IN_REVIEW').length;const totalRevenue=rides.reduce((s,r)=>s+Number(r.estimatedFare||0),0);const metrics=[[t.trips,String(rides.length)],[t.active,String(activeDrivers)],[t.open,String(openSupport)],[t.cities,String(config.cities.length)]];return <main dir={rtl?'rtl':'ltr'} style={{textAlign:rtl?'right':'left'}}><section className='hero'><div className='heroTop'><div><p className='kicker'>Jnbk جنبك {t.cc}</p><h1>{t.dash}</h1><p>{t.hero}</p></div><div className='topActions'><a className='languageSwitch' href={`?lang=${lang==='ar'?'en':'ar'}`}>{t.toggle}</a><a className='languageSwitch' href={`/portal?lang=${lang}`}>{t.portal}</a></div></div></section><section className='grid'>{metrics.map(([l,v])=><div className='card' key={l}><p>{l}</p><strong>{v}</strong></div>)}</section><section className='panel'><h2>{t.portal}</h2><p className='muted'>{t.portalDesc}</p><a className='primaryAction' style={{display:'inline-block',marginTop:12,textDecoration:'none'}} href={`/portal?lang=${lang}`}>{t.portal}</a></section><section className='grid devGrid'><div className='panel'><h2>{t.operations}</h2><p className='muted'>{t.operationsDesc}</p><a className='primaryAction' style={{display:'inline-block',marginTop:12,textDecoration:'none'}} href={`/portal?lang=${lang}`}>{t.operations}</a></div><div className='panel'><h2>{t.settings}</h2><p className='muted'>{t.settingsDesc}</p><a className='primaryAction' style={{display:'inline-block',marginTop:12,textDecoration:'none'}} href={`/portal?lang=${lang}`}>{t.settings}</a></div><div className='panel'><h2>{t.business}</h2><p className='muted'>{t.businessDesc}</p><a className='primaryAction' style={{display:'inline-block',marginTop:12,textDecoration:'none'}} href={`/portal?lang=${lang}`}>{t.business}</a></div><div className='panel'><h2>{t.summary}</h2><div className='table'><div className='row'><span>{t.done}</span><span>{completedRides}</span><span>{t.revenue}</span><b>{totalRevenue} SDG</b></div></div></div></section></main>}
